### ISSUE TITLE
What are the input parameters of getNAVPerShare on the call contract? The returned net asset value seems to be incorrect

### ISSUE THREAD

**Issue by tony122** [Computable-Finance/CoFiX#10]
contract：0xb2b7BeDd7d7fc19804C7Dd4a4E8174C4c73C210d

function：getNAVPerShare(uint256 ethAmount, uint256 erc20Amount) 

Expected value：XToken's Net Asset Value Per Share，Base ETH

I feel that there are some problems with the return value, please help me with your suggestions, thanks!

**Comment by kazamio** [comment]
Sorry for the confusion.

Actually, we have three kinds of `Net Asset Value Per Share` or `np`

https://github.com/Computable-Finance/CoFiX/blob/master/contracts/CoFiXPair.sol#L418-L434

```solidity
// get Net Asset Value Per Share for mint
// only for read, could cost more gas if use it directly in contract
function getNAVPerShareForMint(OraclePrice memory _op) public view returns (uint256 navps) {
    return calcNAVPerShareForMint(reserve0, reserve1, _op);
}

// get Net Asset Value Per Share for burn
// only for read, could cost more gas if use it directly in contract
function getNAVPerShareForBurn(OraclePrice memory _op) external view returns (uint256 navps) {
    return calcNAVPerShareForBurn(reserve0, reserve1, _op);
}

// get Net Asset Value Per Share (no K)
// only for read, could cost more gas if use it directly in contract
function getNAVPerShare(uint256 ethAmount, uint256 erc20Amount) external override view returns (uint256 navps) {
    return calcNAVPerShare(reserve0, reserve1, ethAmount, erc20Amount);
}
```

Check section 4.3 (Market maker net worth of each share(XToken), Np) for details of Np https://github.com/Computable-Finance/Doc#43-market-maker-net-worth-of-each-sharextoken-np.

Basically, we have two kinds of `np`, one at the time of adding liquidity and one at the time of removing liquidity. The difference is in the price, and more precisely in the usage of the `k` value. You'll see that if you look at the `np` formula.

Not sure what you're using np for. The implementation of `getNAVPerShare` ignores the k value and it's an estimated value of `np` when the value of k is not considered.

You should pass the current price as a parameter.

```solidity
getNAVPerShare(uint256 ethAmount, uint256 erc20Amount)
```

The `ethAmount` and `erc20Amount` is coming from the style of nest representing the price ratio of ETH vs some ERC20 token.

Check https://github.com/NEST-Protocol/NEST-oracle-V3/blob/bea6739e5b2c1c3f6d891ff99821be5663ed6517/NestOffer/Nest_3_OfferPrice.sol#L228

You can just use `Nest_3_OfferPrice::checkPriceNow(tokenAddress)` to get the latest price. If you set `tokenAddress` as USDT address, you could get the result like this.

```
[ checkPriceNow method Response ]
  ethAmount   uint256 :  30000000000000000000
  erc20Amount   uint256 :  11084700000
  blockNum   uint256 :  11093408
```

The `ethAmount` and `erc20Amount` is exactly what we wanted here.  It represents `30000000000000000000` ETH worth 
`11084700000` USDT.

We use `NAVPS_BASE` to support decimals.

https://github.com/Computable-Finance/CoFiX/blob/master/contracts/CoFiXPair.sol#L23
```solidity
    uint256 constant public NAVPS_BASE = 1E18; // NAVPS (Net Asset Value Per Share), need accuracy
```

If the current np is `1`, the `getNAVPerShare` actually returns `1e18`. 
If the current np is `0.99`, the `getNAVPerShare` actually returns `0.99*1e18`. 
If the current np is `1.01`, the `getNAVPerShare` actually returns `1.01*1e18`. 

So if you want to get the true value of `np`, you should divide the result you get by `NAVPS_BASE`.

I hope I explained it well. Feel free to ask any more questions.

**Comment by tony122** [comment]
The explanation is great, thank you very much！My problem has been solved and the NP value is correct!
