### ISSUE TITLE
How to estimate the trade result under Nest3.5?

### ISSUE THREAD

**Issue by apiscerena** [Computable-Finance/CoFiX#16]
I used calcK to calcuate the dynamic K value, pass it to oraclePrice, and used oraclePrice to  feed calcOutToken0(amount, oraclePrice). but I could not get the same outToken amount as cofix.io website, why?  Does it relate to theta parameter?

**Comment by kazamio** [comment]
@apiscerena Hi, did you add `impact cost` and theta parameter?

https://github.com/Computable-Finance/CoFiX/blob/master/docs/how_to_integrate_cofix.md#estimated-trade-results

**Comment by apiscerena** [comment]
theta parameter is retrieved using orginal "getKInfo" method right?

**Comment by kazamio** [comment]
> theta parameter is retrieved using orginal "getKInfo" method right?

Yes!

**Comment by apiscerena** [comment]
Got it, thanks mate!

**Comment by apiscerena** [comment]
Got it, thanks mate!
